#set page(
  paper: "a4",
  margin: 2.5cm,
)

#set text(
  size: 11pt,
)

#set par(
  justify: true,
)

= Testing Indecis in Randomly Generated vs Heavily Biased Databases

For this assignment, I used Python to create two databases with data generated by Faker.
The first database contains randomly generated data, while in the second database 50% of all first names were replaced with the mock name "BiasName".

Since variance requires numerical values, calculating the variance of the names themselves would not make sense. Instead, I calculated the variance of the frequencies of the individual names.
The results showed that the biased database has a much higher variance and therefore a much more uneven distribution.

When testing the performance of queries with and without an index, it was clearly visible that the queries ran faster when an index was present.
The tradeoff of using an index is the additional storage space it requires. In my tests, the database size increased significantly after adding the index.

In conclusion, the variance of names cannot be calculated directly in a meaningful way, but the variance of their frequencies can be used to analyze their distribution.
Using an index improves query performance, but this improvement comes at the cost of additional storage.


